# Generated by Django 4.1 on 2022-08-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_remove_workspace_shapes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.ImageField(max_length=255, upload_to='media/'),
        ),
    ]
